// import React from 'react'

// const Page2 = () => {
//   return (
//     <div className=''>
//       Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe facere minus distinctio. Inventore labore pariatur adipisci ullam, iusto unde quam, facere possimus minus quidem eos quisquam modi ea! Voluptatem, quae eum vero at sequi ipsam possimus exercitationem odit odio iusto iure rerum nisi eos necessitatibus non, earum officiis quisquam dolorum saepe unde? Laboriosam aliquam, eius pariatur non dolor reprehenderit blanditiis officiis consequatur repudiandae! Officiis, eligendi. Sit impedit explicabo unde ea laudantium, nesciunt obcaecati numquam! Ad amet laboriosam voluptas iure nostrum sapiente reprehenderit obcaecati vero sunt? Quis esse odio voluptates aperiam voluptas amet officia quos laboriosam molestiae beatae iusto, omnis illum! Eligendi consequuntur aliquam magni itaque corrupti est? Magni nobis nam perferendis iusto, expedita dolorum nemo accusamus amet ipsum voluptatibus. Debitis ab quae, nobis necessitatibus reiciendis dignissimos ex, harum et ratione voluptatum consectetur, soluta quas libero praesentium non rerum at esse similique dolorum dolorem quisquam tenetur? Autem ducimus, ipsa quis excepturi necessitatibus sapiente praesentium eius minus laboriosam? Autem nostrum possimus placeat ad deleniti facilis quam commodi excepturi cum officia saepe consequuntur incidunt dignissimos, dolore rem. Accusantium a cupiditate voluptatem porro ut cumque illo impedit. Eligendi voluptas nulla non, quibusdam aperiam ipsam rerum nisi cum totam impedit tenetur ab est, ea amet qui. Deleniti vel voluptatibus totam ab, porro sint tempore dicta et dolorem! Dolor voluptates dolores eligendi, laudantium odit consequatur alias ipsam id modi sunt non maxime perferendis voluptas unde impedit magnam tenetur ex, commodi reiciendis error nam at voluptate quos totam! Laudantium, minima ratione suscipit, quae illum veritatis iusto expedita soluta ab eos vel ex, eveniet voluptates! Dignissimos quis est, excepturi libero assumenda amet qui accusamus? Perferendis deserunt eligendi, culpa doloribus maxime sint explicabo illum eveniet totam nam tempore voluptatem ipsam, exercitationem natus quas, iure asperiores aliquid placeat est sequi officia aut mollitia? Eligendi cum excepturi facere voluptatibus repudiandae vero!
//     </div>
//   )
// }

// export default Page2
